/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package casino.vista;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JTextField;

/**
 *
 * @author usuario
 */
public class VentanaConfiguracion extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName());

    /**
     * Creates new form VentanaConfiguracion
     */
    public VentanaConfiguracion() {
        initComponents();
    }
   
    //uso de la activación de trampa
    public javax.swing.JCheckBox getChkActDescTrampa() {
    return chkActDescTrampa;
}

    // método que devuelve directamente el estado de la trampa
    public boolean isTrampaActivadaSeleccionada() {
        return chkActDescTrampa.isSelected();
}
    
    //CREAMOS GETTERS PARA TENER ACCESO A LOS COMPONENTES
    public JButton getBtnAgregarJugador() { return btnAgregarJugador; }
    public JTextField getTxtNombreJugador() { return txtNombreJugador; }
    public JTextField getTxtApodo() { return txtApodo; }
    public JComboBox<String> getCmbTipoJugador() { return cmbTipoJugador; }
    public JList<String> getLstJUgadoresRegistrados() { return lstJUgadoresRegistrados; }

    public JButton getBtnJugar() { return btnJugar2; }
    public JButton getBtnCargarPartida() { return btnCargarPartida; }
    public JButton getBtnSalir() { return btnSalir; }
    public JButton getBtnEliminarJugador() { return btnEliminarJugador; }
    public JButton getBtnConfirmarPart() { return bntConfirmarPart; }


    public JTextField getTxtDineroInicial() { return txtDineroInicial; }  
    
    public JCheckBox getChkTrampa() { return chkActDescTrampa; }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpCantidadPartidas = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btnCargarPartida = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnJugar2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtNombreJugador = new javax.swing.JTextField();
        txtApodo = new javax.swing.JTextField();
        cmbTipoJugador = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAgregarJugador = new javax.swing.JButton();
        Jugadores = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstJUgadoresRegistrados = new javax.swing.JList<>();
        btnEliminarJugador = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chkActDescTrampa = new javax.swing.JCheckBox();
        txtDineroInicial = new javax.swing.JTextField();
        bntConfirmarPart = new javax.swing.JButton();
        Op1 = new javax.swing.JRadioButton();
        Op2 = new javax.swing.JRadioButton();
        Op3 = new javax.swing.JRadioButton();
        txtRondasPartidas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCargarPartida.setText("Cargar Partida");

        btnSalir.setText("Salir");

        btnJugar2.setText("Jugar!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnJugar2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnJugar2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCargarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Jugar", jPanel3);

        cmbTipoJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Novato", "Experto", "Vip" }));

        jLabel1.setText("Nombre de jugador");

        jLabel2.setText("Apodo");

        jLabel3.setText("Tipo de jugador");

        btnAgregarJugador.setText("Agregar jugador");

        Jugadores.setText("Jugadores");

        jScrollPane1.setViewportView(lstJUgadoresRegistrados);

        btnEliminarJugador.setText("Eliminar Jugador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreJugador)
                    .addComponent(txtApodo)
                    .addComponent(cmbTipoJugador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Jugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addComponent(btnEliminarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Jugadores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(txtApodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(cmbTipoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnAgregarJugador))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarJugador)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro de Jugadores", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Dinero Incial (default - $500)");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 215, -1));

        jLabel5.setText("Cantidad de partidas a jugar");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 215, -1));

        jLabel6.setText("Rondas por Partida");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 179, -1));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 213, -1, -1));

        chkActDescTrampa.setText("Activar/desactivar trampa");
        jPanel2.add(chkActDescTrampa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 173, -1));
        jPanel2.add(txtDineroInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 240, -1));

        bntConfirmarPart.setText("Listo!");
        jPanel2.add(bntConfirmarPart, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 240, -1));

        bgpCantidadPartidas.add(Op1);
        Op1.setSelected(true);
        Op1.setText("2 Partidas");
        Op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Op1ActionPerformed(evt);
            }
        });
        jPanel2.add(Op1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        bgpCantidadPartidas.add(Op2);
        Op2.setText("3 Partidas");
        Op2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Op2ActionPerformed(evt);
            }
        });
        jPanel2.add(Op2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        bgpCantidadPartidas.add(Op3);
        Op3.setText("5 Partidas");
        Op3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Op3ActionPerformed(evt);
            }
        });
        jPanel2.add(Op3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        txtRondasPartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRondasPartidasActionPerformed(evt);
            }
        });
        jPanel2.add(txtRondasPartidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 240, -1));

        jTabbedPane1.addTab("Configuracion de partidas", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Op1ActionPerformed

    }//GEN-LAST:event_Op1ActionPerformed

    private void Op2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Op2ActionPerformed
    }//GEN-LAST:event_Op2ActionPerformed

    private void Op3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Op3ActionPerformed
    }//GEN-LAST:event_Op3ActionPerformed

    private void txtRondasPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRondasPartidasActionPerformed
    }//GEN-LAST:event_txtRondasPartidasActionPerformed
    
    public javax.swing.ButtonGroup getBgpCantidadPartidas() {
        return bgpCantidadPartidas;
    }
    public javax.swing.JTextField getTxtRondasPartidas() {
        return txtRondasPartidas;
    }
    public javax.swing.JRadioButton getOp1() {
        return Op1;
    }

    public javax.swing.JRadioButton getOp2() {
        return Op2;
    }

    public javax.swing.JRadioButton getOp3() {
        return Op3;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new VentanaConfiguracion().setVisible(true));
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jugadores;
    private javax.swing.JRadioButton Op1;
    private javax.swing.JRadioButton Op2;
    private javax.swing.JRadioButton Op3;
    private javax.swing.ButtonGroup bgpCantidadPartidas;
    private javax.swing.JButton bntConfirmarPart;
    private javax.swing.JButton btnAgregarJugador;
    private javax.swing.JButton btnCargarPartida;
    private javax.swing.JButton btnEliminarJugador;
    private javax.swing.JButton btnJugar2;
    private javax.swing.JButton btnSalir;
    public javax.swing.JCheckBox chkActDescTrampa;
    private javax.swing.JComboBox<String> cmbTipoJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> lstJUgadoresRegistrados;
    private javax.swing.JTextField txtApodo;
    private javax.swing.JTextField txtDineroInicial;
    private javax.swing.JTextField txtNombreJugador;
    private javax.swing.JTextField txtRondasPartidas;
    // End of variables declaration//GEN-END:variables

}
